# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# A guide on how to configure the plugin can be found in the official documentation.
# https://ls.przemus.xyz/
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

heartItem:
  enabled: true
  name: "&c&lExtra Heart"
  material: "RED_DYE"
  lore:
    - "&6Gives an extra heart!"
    - "&7&oYou have ${chance}% to get an additional heart added."
  loseChance: 50
  addLimit: 0
  withdraw-enabled: true

reviveBook:
  enabled: true
  name: "&c&lRevive Book"
  material: "ENCHANTED_BOOK"
  inventory-title: "&a&lRevive player!"
  lore:
    - "&6Revives targeted player!"
  skull-lore:
    - "&aPress on the head to revive."

killHeartLimit: 0
removeHeartOnlyIfKilledByPlayer: false
banOn0Hearts: true
broadcastBanFrom0Hearts: true
banTime: 0
reviveHeartAmount: 20


recipe:
  enabled: true
  recipes:
    1:
      recipe-enabled: true
      item: "extra_heart"
      shaped: true
      extraHeartItemUseSuccess: 100
      discover: false
      items:
        - "DIAMOND_BLOCK"
        - "DIAMOND_BLOCK"
        - "DIAMOND_BLOCK"
        - "DIAMOND_BLOCK"
        - "NETHER_STAR"
        - "DIAMOND_BLOCK"
        - "DIAMOND_BLOCK"
        - "DIAMOND_BLOCK"
        - "DIAMOND_BLOCK"
    2:
      recipe-enabled: true
      item: "revive_book"
      shaped: true
      discover: true
      items:
        - "TOTEM_OF_UNDYING"
        - "TOTEM_OF_UNDYING"
        - "TOTEM_OF_UNDYING"
        - "ENCHANTED_GOLDEN_APPLE"
        - "BOOK"
        - "ENCHANTED_GOLDEN_APPLE"
        - "TOTEM_OF_UNDYING"
        - "TOTEM_OF_UNDYING"
        - "TOTEM_OF_UNDYING"


loot:
  enabled: true
  worlds:
    world:
      chanceForHeartToGenerate: 50
      heartAddChance: 50
      chanceForReviveBookToGenerate: 50
    world_nether:
      chanceForHeartToGenerate: 75
      heartAddChance: 75
      chanceForReviveBookToGenerate: 75
    world_the_end:
      chanceForHeartToGenerate: 100
      heartAddChance: 100
      chanceForReviveBookToGenerate: 100

messages:
  heartReceived: "&a&lYou've received an extra heart!"
  heartGained: "&a&lYou've gained a heart for killing ${player}!"
  heartFailure: "&4&lYou didn't get an extra heart."
  heartLost: "&4&lYou've lost a heart."
  noMoreHeartsBan: "&c&lYou've lost all your hearts."
  bannedNoMoreHeartsBroadcast: "&c&l${player} &4&lhas lost all of their hearts."
  configReloaded: "&aConfig reloaded."
  recipesReloaded: "&aRecipes reloaded."
  lootReloaded: "&aLoot settings reloaded."
  heartRemoved: "&4&lSomeone has taken ${amount}x hearts from you."
  heartRemovedAdmin: "&4&lYou took ${amount}x hearts from ${player}."
  heartAdded: "&a&lSomeone added ${amount}x hearts to you."
  heartAddedAdmin: "&a&lYou added ${amount}x hearts for ${player}."
  heartSetted: "&f&lSomeone set your hearts to ${amount}x."
  heartSettedAdmin: "&f&lYou set the number of hearts to ${amount}x for ${player}."
  heartCheck: "&e&l${player} has ${amount}x hearts."
  banRemoved: "&a&lYou've removed ban from ${player}."
  playerNotFound: "&c&lPlayer not found."
  playerNotBanned: "&c&l${player} is not banned."
  playerNotDead: "&c&l${player} has not been eliminated, so he cannot be revived."
  playerRevived: "&a&lYou have revived &6&l${player}&a&l!"
  maxHeartsFromExtraHeart: "&c&lYou can't get more than ${max}x hearts from an extra heart."
  maxHearts: "&c&lYou can't get more than ${max}x hearts."
  previousPage: "&a&l← Previous Page"
  previousPageLore: "&aClick to move back to page ${page}."
  currentPage: "&7&lPage ${currentPage} of ${maxPage}"
  currentPageLore: "&7You are currently viewing page ${page}."
  nextPage: "&a&lNext Page →"
  nextPageLore: "&aClick to move forward to page ${page}."
  urNotPlayer: "&c&lYou have to be a player to use this."
  featureDisabled: "&c&lThis feature is disabled."
  heartWithdrawn: "&a&lYou've withdrawn a heart."
  abuseDetected: "&c&lOur system has detected that your amount of hearts is higher than the maximum. We've reverted your hearts back to the normal value."

placeholder-api:
  banned-text: "&c&lBanned."
  not-banned-text: "&a&lNot Banned."

custom-commands:
  mode: "disabled"
  onBan:
    - "tellraw @a ${player} got banned!"
  onRevive:
    - "tellraw @a ${revived} got revived by ${reviving}!"